DROP DATABASE IF EXISTS db_javaEE;
CREATE DATABASE db_javaEE;
DROP TABLE IF EXISTS db_javaEE.user;
CREATE TABLE db_javaEE.user(
  id       INT AUTO_INCREMENT PRIMARY KEY
  COMMENT 'ID PK',
  nick     VARCHAR(191) NOT NULL UNIQUE
  COMMENT '昵称',
  mobile   VARCHAR(191) NOT NULL UNIQUE
  COMMENT '手机号',
  password VARCHAR(255) NOT NULL
  COMMENT '密码'
)
  COMMENT '用户表';
SELECT *
FROM db_javaEE.user;